In [4]:
from google.colab import files
uploaded = files.upload()

Saving petrol_consumption (2).csv to petrol_consumption (2).csv
Saving drug (1).csv to drug (1) (1).csv
Saving iris (1) (2).csv to iris (1) (2) (1).csv


In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Load dataset
iris = pd.read_csv("iris (1) (2).csv")

# Features and target
X = iris.drop("species", axis=1)
y = iris["species"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

print("IRIS Accuracy:", accuracy_score(y_test, y_pred))
print("IRIS Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

IRIS Accuracy: 1.0
IRIS Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [6]:
from sklearn.preprocessing import LabelEncoder

# Load dataset
drug = pd.read_csv("drug (1).csv")

# Encode categorical columns
le = LabelEncoder()
drug["Sex"] = le.fit_transform(drug["Sex"])
drug["BP"] = le.fit_transform(drug["BP"])
drug["Cholesterol"] = le.fit_transform(drug["Cholesterol"])
drug["Drug"] = le.fit_transform(drug["Drug"])

# Features and target
X = drug.drop("Drug", axis=1)
y = drug["Drug"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

print("Drug Dataset Accuracy:", accuracy_score(y_test, y_pred))
print("Drug Dataset Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Drug Dataset Accuracy: 1.0
Drug Dataset Confusion Matrix:
[[ 6  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  0 15]]


In [7]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

# Load dataset
petrol = pd.read_csv("petrol_consumption (2).csv")

# Features and target
X = petrol.drop("Petrol_Consumption", axis=1)
y = petrol["Petrol_Consumption"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model
model = DecisionTreeRegressor()
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error:", np.sqrt(mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 86.9
Mean Squared Error: 16923.3
Root Mean Squared Error: 130.08958451774686
